[package]
name = "cifar-10"
version = "0.1.1"
authors = ["chrism <christopher.and.moran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cifar_10"

[features]
default = []
show = ["minifb", "image"]

[dependencies]
ndarray = "0.13"
rand = "0.7"

# Used to show datasets
image = {version = "0.23", optional = true}
minifb = {version = "0.17", optional = true}
