[package]
name = "cifar-ten"
version = "0.1.0"
authors = [
    "Christopher Moran <christopher.and.moran@gmail.com>",
    "Manuel Drehwald"
]
edition = "2018"
repository = "https://github.com/quietlychris/cifar-ten"
readme = "README.md"
license = "MIT"
description = "Parses the CIFAR-10 dataset binary files, and returns them as a Rust ndarray tuple"
keywords = ["data", "machine", "learning", "cifar", "ten"]
exclude = [
    "data/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cifar_ten"

[features]
default = []
show = ["minifb", "image"]

[dependencies]
ndarray = "0.13"
rand = "0.7"

# Used to show datasets
image = {version = "0.23", optional = true}
minifb = {version = "0.17", optional = true}
