name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL2
      run: sudo apt install libsdl2-dev
    - name: Build basic
      run: cargo build --features download
    - name: Build with download feature
      run: cargo build --features=download,to_ndarray  
    - name: Run tests
      run: cargo test --verbose --features=download,to_ndarray -- --test-threads=1
    - name: Build examples
      run: cargo build --examples --all --features=download,to_ndarray
